version: "3.9"

services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-app

  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/SurgeGlobal
      - PORT=5000
      - JWT_SECRET=ThisIsAJwtSecretAndItShouldBeLongAndSecure
      - ADMIN_MAIL=heshanmadurnga1@gmail.com
      - ADMIN_MAILAPP_PASSWORD=zgvfleuizcajuhcv

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongodb:
    driver: local
